### ISSUE TITLE
Misleading line here

### ISSUE THREAD

**Issue by jayrulez** [NVIDIAGameWorks/NRI#1]
https://github.com/NVIDIAGameWorks/NRI/blob/64120b73fff99de567372d43915f6409783f707a/Source/VK/BufferVK.cpp#L26

The left hand side is being compared with a VK_NULL_HANDLE on the right. This works as VK_NULL_HANDLE is defined as nullptr anyway. However, the line is misleading as looking at it without IDE, one would assume that m_Memory is a vulkan resource when it is in fact a NRI struct.

**Comment by dzhdanNV** [comment]
Sorry, I slipped out from my attention. Thanks, it will be fixed soon.

**Comment by dzhdanNV** [comment]
Thanks Robert. Fixed.
