### ISSUE TITLE
m_DescriptorSets needs to be cleared after deallocating the entries in Reset

### ISSUE THREAD

**Issue by jayrulez** [NVIDIAGameWorks/NRI#10]
https://github.com/NVIDIAGameWorks/NRI/blob/171b583f92c5021ec56f384392d9d552ef105cba/Source/D3D12/DescriptorPoolD3D12.cpp#L136

Otherwise, you will do a double free when the destructor is called which tries to deallocate all items in the list.

**Comment by dzhdanNV** [comment]
Many thanks! Again ^ 2. Definitely will be fixed.

**Comment by dzhdanNV** [comment]
Fixed. Thanks for your help!
