### ISSUE TITLE
Windows AMD Vulkan Validation.

### ISSUE THREAD

**Issue by pollend** [NVIDIAGameWorks/NRI#101]
I'm running into this validation error for window/AMD/Vulkan: https://gist.github.com/pollend/9cfe8a57d8a521d18e40e62b79e676a7

not sure why this extension doesn't get excluded when you check for it support. 

I've just been commenting out this line just to get things working for the moment. 
```
    // VkPhysicalDeviceMaintenance5FeaturesKHR maintenance5Features = {VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_5_FEATURES_KHR};
    // if (IsExtensionSupported(VK_KHR_MAINTENANCE_5_EXTENSION_NAME, desiredDeviceExts)) {
    //     APPEND_EXT(maintenance5Features);
    //     m_IsSupported.maintenance5 = true;
    // }
```

**Comment by dzhdanNV** [comment]
Currently looks like an issue on AMD side, because `VK_KHR_maintenance5` is reported as supported in your log:
```
nri::INFO (DeviceVK.hpp:181) - VK::AMD  Radeon RX 7800 XT -     VK_KHR_maintenance5 (v1)
```

**Comment by dzhdanNV** [comment]
I have to ask - do you use latest VK SDK and AMD drivers?
