### ISSUE TITLE
"Copy AMD AGS into the output folder" must be only if NRI_ENABLE_EXTERNAL_LIBRARIES is ON

### ISSUE THREAD

**Issue by ilyachastikov** [NVIDIAGameWorks/NRI#108]
If NRI_ENABLE_EXTERNAL_LIBRARIES is OFF and AMD_AGS_DLL is not copied to project then will be error. Cause "Copy AMD AGS into the output folder" must be only if NRI_ENABLE_EXTERNAL_LIBRARIES is ON.

**Comment by dzhdanNV** [comment]
Thanks! Fixed.
