### ISSUE TITLE
Is descriptor indexing supported?

### ISSUE THREAD

**Issue by ilyachastikov** [NVIDIAGameWorks/NRI#109]
Is descriptor indexing supported? I can't to find this feature in code of the lib.

**Comment by dzhdanNV** [comment]
Descriptor indexing is supported (obviously it's a must for ray tracing at least):
- NRI: `DeviceDesc::bindlessTier`
- VK: search for `uint32_t descriptorIndexing : 1;`
- D3D12: besides basic support:
```c++
    if (device.GetDesc().shaderModel >= 66)
        flags |= D3D12_ROOT_SIGNATURE_FLAG_CBV_SRV_UAV_HEAP_DIRECTLY_INDEXED | D3D12_ROOT_SIGNATURE_FLAG_SAMPLER_HEAP_DIRECTLY_INDEXED;
```
Please, clarify the question, if you mean something else.

**Comment by ilyachastikov** [comment]
Thanks for answer. I looked carefully and figured it out. I suppose this feature can be mentioned in readme.md for clarity.

**Comment by dzhdanNV** [comment]
Hmm, NRI pretends to be "feature complete" implicitly, i.e. without a need to say "hey, we have finally added descriptor indexing support" (but sampler feedback and sparse resources features are still not there yet). Moreover, "ray tracing support" implies "descriptor indexing support". But nevertheless I don't mind to modify README a bit:
```
Key features:
 - *C++* and *C* compatible interfaces
 - generalized common denominator for D3D12, VK and D3D11 GAPIs
 - low overhead
 - descriptor indexing support <=========================== added
 - ray tracing support
 - mesh shaders support
```
Does it look good for you?

**Comment by ilyachastikov** [comment]
Yes. I think it look good.

**Comment by dzhdanNV** [comment]
Thanks! Committed.
