### ISSUE TITLE
Incorrect cast

### ISSUE THREAD

**Issue by jayrulez** [NVIDIAGameWorks/NRI#11]
https://github.com/NVIDIAGameWorks/NRI/blob/171b583f92c5021ec56f384392d9d552ef105cba/Source/D3D12/CommandBufferD3D12.cpp#L520

This line and the one below should be casting to TextureD3D12*, not BufferD3D12*

**Comment by dzhdanNV** [comment]
Many thanks! Again! Will be fixed.

**Comment by dzhdanNV** [comment]
Fixed locally.

**Comment by dzhdanNV** [comment]
Fixed. Thanks for your help!
