### ISSUE TITLE
Parameter type should be NRIVkSemaphore here

### ISSUE THREAD

**Issue by jayrulez** [NVIDIAGameWorks/NRI#12]
https://github.com/NVIDIAGameWorks/NRI/blob/0f3c47b0525a97e50bf8cc532b24a4d0794ed8a4/Source/VK/DeviceSemaphoreVK.cpp#L43

**Comment by dzhdanNV** [comment]
Many thanks! Again :) Will be fixed.

**Comment by dzhdanNV** [comment]
I fixed it locally.  `NRIVkFence` should be used instead of `NRIVkSemaphore`.

**Comment by dzhdanNV** [comment]
Fixed. Thanks for your help!
