### ISSUE TITLE
Improved Metal / Apple Silicon Support

### ISSUE THREAD

**Issue by johnpars** [NVIDIAGameWorks/NRI#14]
Hi, I have been taking this abstraction for a spin (thank you for making it), and in order for it to work on the M1 MacBook I am using, I needed to adjust Vulkan instance and device creation to correctly utilize the `VK_KHR_portability_enumeration/subset` extension.

**Comment by dzhdanNV** [comment]
Getting Apple on board is definitely worth it. Which changes did you made? I'm ready to integrate :)

**Comment by johnpars** [comment]
I had to make various changes in ShaderMake, NRI, NRI Framework, and MathLib for it to work (M1 MacBook, Sonoma 14.0). 

I can make the PRs when I have time, in the meantime I have forks of those repos where you can see the exact changes. :)

**Comment by dzhdanNV** [comment]
Thanks. Understood. I will definitely look at your forks.

**Comment by dzhdanNV** [comment]
@johnpars I integrated changes from your fork and updated GitHub! Tons of thanks! Feel free to fix more :D

**Comment by dzhdanNV** [comment]
Also I'm looking at other forks. It will take a bit more time. I will update GitHub repos soon.

**Comment by johnpars** [comment]
That's great, I'll try it soon. Thanks!
