### ISSUE TITLE
ReBAR support

### ISSUE THREAD

**Issue by vertver** [NVIDIAGameWorks/NRI#25]

**Comment by dzhdanNV** [comment]
Link to the discussion: https://github.com/NVIDIAGameWorks/NRI/issues/24#issuecomment-1905201150

Actually there is `D3D12_HEAP_TYPE_GPU_UPLOAD`, what greatly simplified things.

**Comment by vertver** [comment]
> Actually there is D3D12_HEAP_TYPE_GPU_UPLOAD, what greatly simplified things.

I also wanted to quote this heap type [(some info about this heap type here)](https://microsoft.github.io/DirectX-Specs/d3d/D3D12GPUUploadHeaps.htm)).

**Comment by vertver** [comment]
The AGS SDK doesn't seem to support GPU Heaps, so I think it may only be available on NVIDIA GPUs in D3D11.

**Comment by dzhdanNV** [comment]
`D3D12_HEAP_TYPE_GPU_UPLOAD` is not available even in the latest Win SDK. Let me understand what Agility SDK is...
P.S. Link in your post is broken...

**Comment by vertver** [comment]
> P.S. Link in your post is broken...
fixed
> what Agility SDK is
This is an optional package for WinSDK for experimental functions at runtime or in the compiler, such as wave matrices or video decoding.

**Comment by dzhdanNV** [comment]
Agility SDK is awful. Instead of adding an ability to download and install D3D SDK update (what MS calls Agility SDK) into a specific folder (like VK SDK, like VS redistributable), they put this burden on users, which have to include it in their apps. This model suits for games, but is worse for NRI-like projects. It seems to me that we will have to either ask to install Agility SDK into a specific folder or just starting redistributing it with NRI, what is just wrong. I will discuss with colleagues how to proceed better...

**Comment by dzhdanNV** [comment]
> Enhanced Barriers. What do you think?

IMO, minimal performance gains in exchange of maximum pain in the ass. But, unfortunately, we should move into this direction... no rush though :) Feel free to create a separate issue for this. E-barriers == VK-style barriers. VK-style barriers are already in NRI, so should not be difficult to migrate, assuming no surprises...

**Comment by dzhdanNV** [comment]
A short update - I'm trying to find the best way of linking with Agility SDK. My plan is to get it working today.

**Comment by vertver** [comment]
Sounds good. Let me know when you get something going.

**Comment by dzhdanNV** [comment]
I compiled NRI/D3D12 with Agility SDK. Here is what I added to the README:

====================================================================

## CMAKE OPTIONS

- `NRI_STATIC_LIBRARY` - build NRI as a static library (`off` by default)
- `NRI_BACKEND_VK` - enable VULKAN backend (`on` by default)
- `NRI_BACKEND_D3D11` - enable D3D11 backend (`on` by default on Windows)
- `NRI_BACKEND_D3D12` - enable D3D12 backend (`on` by default on Windows)

Vulkan only:
- `NRI_DISABLE_XLIB_SUPPORT` - disable *Xlib* support (`off` by default)
- `NRI_DISABLE_WAYLAND_SUPPORT` - disable *Wayland* support (`off` by default)

D3D12 only:
- `NRI_AGILITY_SDK_PATH` - path to a directory containing Agility SDK: contents of `.nupkg/build/native/` (`C:/AgilitySDK` by default)
- `NRI_AGILITY_SDK_VERSION` - Agility SDK version (`611` by default, can be newer)
- `NRI_AGILITY_SDK_DIR` - directory where Agility SDK binaries will be copied to relative to `CMAKE_RUNTIME_OUTPUT_DIRECTORY` (`AgilitySDK` by default)

## AGILITY SDK

*Overview* and *Download* sections can be found [*here*](https://devblogs.microsoft.com/directx/directx12agility/).

D3D12 backend requires Agility SDK to get access to most recent D3D12 features. As soon as these features become available in the OS, installation of Agility SDK will be deprecated.

Installation tips:
- download Agility SDK package
    - set `NRI_AGILITY_SDK_VERSION` to the version of the package
- rename `.nupkg` into `.zip`
- copy contents of `.nupkg/build/native` into `NRI_AGILITY_SDK_PATH` folder
    - can be located anywhere
- set `NRI_AGILITY_SDK_DIR` to a path, where `bin` folder needs to be copied
    - most likely closer to the executable
- include auto-generated `NRIAgilitySDK.h` header in the code of your executable

====================================================================
Does it look acceptable? I made some experiments and based on restrictions of Agility SDK and Windows itself didn't manage to find a better solution.

**Comment by vertver** [comment]
I think this is acceptable. If you're already doing ReBAR support, I'll try to do something with tiled texture support and after that Enhanced Barriers.
P.S. Can you answer my question in #26?

**Comment by dzhdanNV** [comment]
Realized how bad is the design of Agility SDK:
- developer mode required for a preview of A-SDK (preview of preview ^_^)
- manual copying mambo-jumbo because the package is `.nupkg`
- various Windows restrictions preventing to create "symbolic links" without Admin rights
- Agility SDK can't be loaded from "another drive"

As the result, I made Agility SDK an optional feature. At least `DEVICE_UPLOAD` (aka GPU upload heap) will softly fallback into `HOST_UPLOAD` if A-SDK is not enabled. Updated README to reflect the changes.

P.S. Answered :)

**Comment by vertver** [comment]
> At least DEVICE_UPLOAD (aka GPU upload heap) will softly fallback into HOST_UPLOAD if A-SDK is not enabled. Updated README to reflect the changes.

I've thought about this behaviour too, and it seems really reasonable. Also, how about supporting BAR without ReBAR via a separate heap for Vulkan as I showed you before?

**Comment by dzhdanNV** [comment]
Let me understand how it works in VK. Must current understanding that I just need to find a heap with proper "memory flags". If I'm right, it will work out of the box. Even if ReBAR is disabled, at least NV driver exposes 256 Mb of BAR memory.

**Comment by vertver** [comment]
> Even if ReBAR is disabled, at least NV driver exposes 256 Mb of BAR memory.

Exactly! You can use this separate heap as upload heap.

**Comment by dzhdanNV** [comment]
Exposed `MemoryLocation::DEVICE_UPLOAD` in `v1.115` with silent fallback to `HOST_UPLOAD`:
- VK: `DEVICE_BIT` is "desired" for `DEVICE_UPLOAD` memory location
- D3D12: `GPU_UPLOAD` is available only if NRI is compiled with enabled Agility SDK support (fallback works in any case)
- D3D11: no support, `HOST_UPLOAD` is used
