### ISSUE TITLE
Seems wrong value is being copied

### ISSUE THREAD

**Issue by jayrulez** [NVIDIAGameWorks/NRI#3]
https://github.com/NVIDIAGameWorks/NRI/blob/64120b73fff99de567372d43915f6409783f707a/Source/VK/CommandBufferVK.cpp#L190

This line seems suspicious. Maybe you should be copying &desc.value?

**Comment by dzhdanNV** [comment]
Sorry, it slipped out from my attention. Thanks, it will be fixed soon.

**Comment by dzhdanNV** [comment]
Thanks Robert. Fixed.
