### ISSUE TITLE
Feature request: Add support for VK_KHR_dynamic_rendering

### ISSUE THREAD

**Issue by jayrulez** [NVIDIAGameWorks/NRI#4]
https://www.khronos.org/blog/streamlining-render-passes

**Comment by dzhdanNV** [comment]
Thanks. We (NRI devs) will think about it.

**Comment by dzhdanNV** [comment]
Sorry for super delay. It will be implemented, yes, and render passes will be removed. It's not a high priority task, but we are interested.

**Comment by dzhdanNV** [comment]
_Kept you waiting, huh?_ Implemented: `FrameBuffer` has been removed from NRI API.
