### ISSUE TITLE
Unsupported depth bounds

### ISSUE THREAD

**Issue by 01Pollux** [NVIDIAGameWorks/NRI#40]
The new 1.118 update broke support for some hardwares where depth bounds isn't supported.
Rather than checking if version is greater than 1, it should have been `D3D12_FEATURE_DATA_D3D12_OPTIONS2::DepthBoundsTestSupported`
This also raises the question of other versions check like sample positions.

https://github.com/NVIDIAGameWorks/NRI/blob/1d52b40bbf46d895457eecce29b1f20977f4d244/Source/D3D12/CommandBufferD3D12.cpp#L297-L301

**Comment by dzhdanNV** [comment]
Thanks. Yes, you are right. But to be honest this code has always been there. I will fix both problems shortly.

**Comment by dzhdanNV** [comment]
Fixed.
