### ISSUE TITLE
Documentation access

### ISSUE THREAD

**Issue by jayrulez** [NVIDIAGameWorks/NRI#5]
What are the requirements for getting to the documentation here?

https://docs.google.com/document/d/1OidQtZnm-3grhua7Oy1WKDUzh8ExTdbO83VTAWS_nNM/

**Comment by a3YsM5jc** [comment]
Added programming guide in NRI v1.82. (commit: c82f6f90b41060437a4f883e5212b687e7f4cca0)

**Comment by a3YsM5jc** [comment]
[ProgrammingGuide.md](https://github.com/NVIDIAGameWorks/NRI/blob/main/ProgrammingGuide.md)
