### ISSUE TITLE
Bug: X11 and Wayland should be treated mutually exclusive during swapchain creation

### ISSUE THREAD

**Issue by nvmheyer** [NVIDIAGameWorks/NRI#54]
https://github.com/NVIDIAGameWorks/NRI/blob/919412b61114f737a7ac984cd909fd31bced3953/Source/VK/SwapChainVK.cpp#L103

This code is broken, if both, X11 and Wayland are available on a system.
NRWindow is a union, so writing to it via

```
        m_NRIWindow.x11.dpy = glfwGetX11Display();
        m_NRIWindow.x11.window = glfwGetX11Window(m_Window);
```

Will make the code in `SwapChainVK::Create()`  think, that we provided both, a X11 and a Wayland window handle. The code will then decide to create a X11 surface object first, followed by overwriting the surface handle by creating yet another Wayland surface object with the same X11 window handle. On NVIDIA drivers this will later lead vkCreateSwapchainKHR() to crash deep in the callstack.

I think, making NRWindow not be a union and instead use #ifdef to control the platform-dependent members would be the right call.

**Comment by dzhdanNV** [comment]
Hi! You are right. Sorry for the lack of testing in this area. I will fix the problem in a few days (have other tasks to do, will try to prioritize).
