### ISSUE TITLE
How does recycling CPU visible descriptors work in NRI?

### ISSUE THREAD

**Issue by anderswk-ioi** [NVIDIAGameWorks/NRI#6]
On destroying a DescriptorD3D12 it seems like the DescriptorHandle is never returned to DeviceD3D12::m_DescriptorPool?

https://github.com/NVIDIAGameWorks/NRI/blob/738865778486fba124b0714f50dda6a72e5d107f/Source/D3D12/DeviceD3D12.cpp#L582

**Comment by a3YsM5jc** [comment]
Fixed in NRI v1.82. (commit: c82f6f90b41060437a4f883e5212b687e7f4cca0)
