### ISSUE TITLE
[RFE] Draw Indirect Count

### ISSUE THREAD

**Issue by vertver** [NVIDIAGameWorks/NRI#65]
Sometimes it's useful to have an indirect buffer count, so that only the required number of draw calls or shader executions are executed.

Links: 
https://github.com/gpuweb/gpuweb/pull/1949
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDrawIndirectCount.html

**Comment by vertver** [comment]
Implementation - https://github.com/NVIDIAGameWorks/NRI/pull/66
Sample - https://github.com/vertver/NRISamples/commit/9d817fe92b78ec137f77f09937b32db9411d1249

**Comment by dzhdanNV** [comment]
Merged. Thank you!
