### ISSUE TITLE
(VULKAN 1.3) Crash when trying to load global commands with vkGetInstanceProcAddr in VkDevice.cpp

### ISSUE THREAD

**Issue by RMichelsen** [NVIDIAGameWorks/NRI#7]
When using a VkInstance created with `VK_API_VERSION_1_3`, vkGetInstanceProcAddr returns a nullptr and thus crashes here:
https://github.com/NVIDIAGameWorks/NRI/blob/main/Source/VK/DeviceVK.cpp#L1973

I suspect that vkGetInstanceProcAddr should not be called with `VkCreateInstance`, `EnumerateInstanceExtensionProperties` and `EnumerateInstanceLayerProperties` as they are global commands and therefore are expected to return `NULL` as per: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#vkGetInstanceProcAddr

For VK_API_VERSION_1_2 this seems to work, although to me it looks like it shouldn't according to the spec?

**Comment by RMichelsen** [comment]
I've read the table wrong - a function pointer should indeed be returned. I'm not sure why it isn't for me, but I suspect it's a user error. Closing the issue due to this.

**Comment by RMichelsen** [comment]
Some clarification after discussing the issue on the Vulkan Discord:

According to the spec VkInstance must be NULL when getting global commands such as `VkCreateInstance` (https://github.com/NVIDIAGameWorks/NRI/blob/main/Source/VK/DeviceVK.cpp#L1973). This has not been enforced before VkInstances created with `VK_API_VERSION_1_3` and thus the crash happens only when creating an instance with version >= 1.3. I'll reopen the issue because I believe this is still a bug, and should be fixed.

**Comment by a3YsM5jc** [comment]
@RMichelsen, thank you for reporting this.

Here are screenshots from VK 1.2 spec:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/92825767/161800763-0d250706-3a17-4b5e-b13e-adf651cbfd90.png">
<img width="693" alt="image" src="https://user-images.githubusercontent.com/92825767/161800690-a6def0b8-f2c2-4050-9922-9d00eec81eae.png">

And I see the same in the VK 1.3 spec. So I think it's valid to query global commands using NULL instance.

Please let me know if I'm missing something.

I've also tried creating a VkInstance with VK_API_VERSION_1_3 in NRI and it worked fine on my machine.
(Windows 10 x64, NV driver 512.15)

**Comment by RMichelsen** [comment]
@a3YsM5jc You are right but I believe the issue is that NRI does not pass a NULL instance, it passes the user-given instance. Or am I mistaken?

**Comment by a3YsM5jc** [comment]
Fixed in NRI v1.82. (commit: c82f6f90b41060437a4f883e5212b687e7f4cca0)
