### ISSUE TITLE
Destructor not actually freeing allocated descriptor sets for DescriptorPoolVK

### ISSUE THREAD

**Issue by jayrulez** [NVIDIAGameWorks/NRI#8]
@dzhdanNV   The code here seems to be incorrect:

https://github.com/NVIDIAGameWorks/NRI/blob/main/Source/VK/DescriptorPoolVK.cpp#L31-L32

It seems it should be attempting to free 0-m_UsedSets instead of m_UsedSets-m_AllocatedSets.size()  (which is the same in some cases.)

**Comment by a3YsM5jc** [comment]
Fixed in NRI v1.82. (commit: c82f6f90b41060437a4f883e5212b687e7f4cca0)
