### ISSUE TITLE
This line seems wrong. Looks like geometry shader should be filled instead.

### ISSUE THREAD

**Issue by jayrulez** [NVIDIAGameWorks/NRI#9]
https://github.com/NVIDIAGameWorks/NRI/blob/0d00b9dc2a48766b9ad15c191ed38ada2d1eb23a/Source/D3D12/PipelineD3D12.cpp#L122

**Comment by dzhdanNV** [comment]
Thanks a lot! Sorry, I missed it. Yeah, a silly typo. I will try to update GitHub as soon as possible.
