### ISSUE TITLE
Push Descriptors

### ISSUE THREAD

**Issue by vertver** [NVIDIAGameWorks/NRI#92]
Since Vulkan has [VK_KHR_push_descriptor](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_push_descriptor.html) extension, it seems reasonable to implement this feature on top of D3D12. However, D3D12 [doesn't support SRV and UAV textures and typed buffers](https://learn.microsoft.com/en-us/windows/win32/direct3d12/using-descriptors-directly-in-the-root-signature) (or texel buffer in Vulkan) in root parameters, so the implementation must also respect this.

**Comment by dzhdanNV** [comment]
Thanks. Implemented.
