### ISSUE TITLE
Expose "Bindless Resources" support in DeviceDesc

### ISSUE THREAD

**Issue by vertver** [NVIDIAGameWorks/NRI#93]
There are 3 tiers of bindless resources:
1st tier: variable array with descriptors using indexing
2nd tier: [Vulkan's BufferRef](https://microsoft.github.io/hlsl-specs/proposals/0010-vk-buffer-ref.html) or [DirectX's Dynamic Resources](https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_6_DynamicResources.html)

The first and second levels are available on devices that support [VK_EXT_descriptor_indexing](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_descriptor_indexing.html), which covers 58.94% of all devices. The second tier is highly experimental and not available on most devices.

**Comment by dzhdanNV** [comment]
Thanks. `bindlessTier` has been added to `DeviceDesc`.
